version: '3'

services:
  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
    - DOCKER_INFLUXDB_INIT_MODE=setup
    - DOCKER_INFLUXDB_INIT_USERNAME=my-user
    - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
    - DOCKER_INFLUXDB_INIT_ORG=my-org
    - DOCKER_INFLUXDB_INIT_BUCKET=k6
    - DOCKER_INFLUXDB_INIT_RETENTION=1w
    - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana/dashboards:/var/lib/grafana/dashboards
      - ./data/grafana/provisioning:/etc/grafana/provisioning  # For automatic dashboard import
      - ./data/grafana/:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin_password  # Set your own password
    depends_on:
      - influxdb
    restart: always

volumes:
  influxdb_data:
